server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shiftsync_db}
    username: ${DB_USERNAME:shiftsync}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:3}
      minimum-idle: ${HIKARI_MIN_IDLE:1}
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    baseline-on-migrate: true
    table: flyway_schema_history_auth

app:
  security:
    jwt:
      private-key-path: classpath:keys/private.pem
      public-key-path: classpath:keys/public.pem
      access-expiration-ms: 900000 # 15 minutes
      refresh-expiration-ms: 2592000000 # 30 days
